# Generated by Django 5.2 on 2025-04-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_bio_grapht_user_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Pending', 'Pending'), ('Not Registered', 'Not Registered')], default='pending', max_length=14),
        ),
    ]
